## Create a new user mode for clipboard specific tasks.
declare-user-mode clipboard
map global normal + ':enter-user-mode clipboard<ret>'

map global clipboard P '! cat /tmp/clipboard<ret>' \
    -docstring "paste the content of the clipboard before the main cursor"
map global clipboard p '<a-!> cat /tmp/clipboard<ret>' \
    -docstring "paste the content of the clipboard after the main cursor"

## Always yank to clipboard
hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_main_reg_dquote" > /tmp/clipboard
}}

## The we use ":" more than ";" so lets invert them.
map global normal <semicolon> ':'
map global normal ':' <semicolon>

## Add relative line numbering.
add-highlighter global/ number-lines -relative -hlcursor

## Add matching character highlighter.
add-highlighter global/ show-matching

## Tell kak where to autoload the plugin manager.
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# Now skip loading the plug.kak since its already loaded.
plug "andreyorst/plug.kak" noload

## Install the kak-lsp plugin.
plug "ul/kak-lsp" do %{
    cargo install --locked --force --path .
}

## Enable the language server support for given file types.
hook global WinSetOption filetype=(rust|c|cpp) %{
    lsp-enable-window

    # Remap some of the lsp space commands.
    map global lsp r '<esc>: lsp-rename-prompt<ret>' \
        -docstring 'rename symbol under main cursor'
    map global lsp R '<esc>: lsp-references<ret>' \
        -docstring 'list symbol references'

    # Add a key to enter the language server namespace. We overwrite the key <,>
    # used by the empty default user mode.
    map global normal <,> ':enter-user-mode<space>lsp<ret>'
}

## Replace tabs by spaces.
plug "andreyorst/smarttab.kak" defer smarttab %{
    # when `backspace' is pressed, 4 spaces are deleted at once
    set-option global softtabstop 4
} config %{
    hook global WinSetOption filetype=.* expandtab
}

## Add fzf as our fuzzy search.
plug "andreyorst/fzf.kak"

## Add some themes.
plug "andreyorst/base16-gruvbox.kak" noload do %{
    mkdir -p $HOME/.config/kak/colors
    find $PWD -type f -name "*.kak" -exec ln -sf {} $HOME/.config/kak/colors/ \;
} config %{
    colorscheme base16-gruvbox-dark-medium
}

## Make the primary highligh of this theme more readable.
set-face global PrimarySelection rgb:000000,rgb:fbf1c7+rFga

## Add highlight to column 80.
add-highlighter global/ column 80 rgb:282828,rgb:fbf1c7+r
