## Create a new user mode for clipboard specific tasks.
declare-user-mode clipboard
map global normal <+> ':enter-user-mode<space>clipboard<ret>'

map global clipboard P '! xsel --output --clipboard<ret>' \
    -docstring "paste the content of the clipboard before the main cursor"
map global clipboard p '<a-!> xsel --output --clipboard<ret>' \
    -docstring "paste the content of the clipboard before the main cursor"

## Add relative line numbering.
add-highlighter global/ number-lines -relative

## Tell kak where to autoload the plugin manager.
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# Now skip loading the plug.kak since its already loaded.
plug "andreyorst/plug.kak" noload

## Install the kak-lsp plugin.
plug "ul/kak-lsp" do %{
    cargo install --locked --force --path .
}

## Enable the language server support for given file types.
hook global WinSetOption filetype=(rust|c|cpp) %{
    lsp-enable-window

    # Remap some of the lsp space commands.
    map global lsp r '<esc>: lsp-rename-prompt<ret>' \
    	-docstring 'rename symbol under main cursor'
    map global lsp R '<esc>: lsp-references<ret>' \
    	-docstring 'list symbol references'

    # Add a key to enter the language server namespace. We overwrite the key <,>
    # used by the empty default user mode.
    map global normal <,> ':enter-user-mode<space>lsp<ret>'
}

## Replace tabs by spaces.
plug "andreyorst/smarttab.kak" defer smarttab %{
    # when `backspace' is pressed, 4 spaces are deleted at once
    set-option global softtabstop 4
} config %{
    hook global WinSetOption filetype=(rust|markdown|kak|sh|c|c++) expandtab
}

## Add fzf as our fuzzy search.
plug "andreyorst/fzf.kak"

## Add the equivalent of VIM's visual block mode.
plug "occivink/kakoune-vertical-selection"

# Overwrite the default view commands since they are basically
# useless.
unmap global normal v
unmap global normal V
map global normal v ': vertical-selection-down<ret>'
map global normal V ': vertical-selection-up<ret>'

## Add some themes.
plug "andreyorst/base16-gruvbox.kak" noload do %{
    mkdir -p $HOME/.config/kak/colors
    find $PWD -type f -name "*.kak" -exec ln -sf {} $HOME/.config/kak/colors/ \;
} config %{
    colorscheme base16-gruvbox-dark-medium
}

## Make the primary highligh of this theme more readable.
set-face global PrimarySelection rgb:000000,rgb:fbf1c7+rFga

## Add highlight to column 80.
add-highlighter global/ column 80 rgb:282828,rgb:fbf1c7+r
